basePath: /api/v1
definitions:
  models.AllItemsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.BaseItemResponse'
        type: array
    type: object
  models.AuthResponse:
    properties:
      token:
        example: ajiji1j98a
        type: string
      user:
        $ref: '#/definitions/models.BaseUserResponse'
    type: object
  models.BaseItemResponse:
    properties:
      category_id:
        example: 1
        type: integer
      counter:
        example: 数
        type: string
      created_at:
        example: "2022-05-01T17:23:17.494039+09:00"
        type: string
      deleted_at:
        example: ""
        type: string
      description:
        example: This is a test item
        type: string
      id:
        example: 1
        type: integer
      name:
        example: test item
        type: string
      number:
        example: 1
        type: integer
      status:
        example: 0
        type: integer
      updated_at:
        example: "2022-05-01T17:23:17.494039+09:00"
        type: string
    type: object
  models.BaseUserResponse:
    properties:
      created_at:
        example: "2022-05-01T17:23:17.494039+09:00"
        type: string
      deleted_at:
        example: ""
        type: string
      email:
        example: test@example.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: test user
        type: string
      updated_at:
        example: "2022-05-01T17:23:17.494039+09:00"
        type: string
    type: object
  models.DeleteUserRequest:
    properties:
      password:
        example: password
        type: string
    type: object
  models.ItemResponse:
    properties:
      item:
        $ref: '#/definitions/models.BaseItemResponse'
    type: object
  models.MutationItemRequest:
    properties:
      category_id:
        example: 1
        type: integer
      counter:
        example: 個
        type: string
      description:
        example: This is a test item
        type: string
      name:
        example: test item
        type: string
      number:
        example: 1
        type: integer
      status:
        example: 0
        type: integer
    type: object
  models.SignInRequest:
    properties:
      email:
        example: test@example.com
        type: string
      password:
        example: password
        type: string
    type: object
  models.SignUpRequest:
    properties:
      email:
        example: test@example.com
        type: string
      name:
        example: test user
        type: string
      password:
        example: password
        type: string
    type: object
  models.UpdatePasswordRequest:
    properties:
      new_password:
        example: newPassword
        type: string
      password:
        example: password
        type: string
    type: object
  models.UpdateUserRequest:
    properties:
      email:
        example: test@example.com
        type: string
      name:
        example: test user
        type: string
    type: object
  models.UserResponse:
    properties:
      user:
        $ref: '#/definitions/models.BaseUserResponse'
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the ToBuyApp server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger ToBuyApp API
  version: "1.0"
paths:
  /items:
    get:
      description: Fetch all items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AllItemsResponse'
        "404":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Fetch all items
      tags:
      - fetchAllItems
    post:
      consumes:
      - application/json
      description: Create user's item
      parameters:
      - description: Create Item Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.MutationItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ItemResponse'
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Create item
      tags:
      - createItem
  /items/{id}:
    get:
      description: Fetch user's item by id
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemResponse'
        "404":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Fetch item by id
      tags:
      - fetchItemBuyId
  /items/{id}/delete:
    post:
      consumes:
      - application/json
      description: Delete user's item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Delete item
      tags:
      - deleteItem
  /items/{id}/update:
    post:
      consumes:
      - application/json
      description: Update user's item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Item Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.MutationItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemResponse'
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Update item
      tags:
      - updateItem
  /me/delete:
    post:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: Delete User Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.DeleteUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Delete User
      tags:
      - deleteUser
  /me/update:
    post:
      consumes:
      - application/json
      description: Update user's information
      parameters:
      - description: Update User Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Update User
      tags:
      - updateUser
  /me/update/password:
    post:
      consumes:
      - application/json
      description: Update user's password
      parameters:
      - description: Update User's Password Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      security:
      - JWT: []
      summary: Update Password
      tags:
      - updatePassword
  /signin:
    post:
      consumes:
      - application/json
      description: SignIn
      parameters:
      - description: SignIn Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: SignIn
      tags:
      - signIn
  /signup:
    post:
      consumes:
      - application/json
      description: SignUp
      parameters:
      - description: SignUp Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: SignUp
      tags:
      - signUp
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
